title: ISO Training
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5910624
  brandStrength: 0.8010118
  lightness: 0.6281619
  brandColors:
    - '#FFFFFF'
    - '#ACACAC'
    - '#005095'
    - '#555756'
    - '#00264A'
  rhythmicContrast: 0.4974705
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: ISO Training
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4544688
layout_spectrum: 0.123946
