name: ISO Training
favicon: null
layout_spectrum: 0.90471
typography_spectrum: 0.38305
title: ISO Training
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7a9a8'
    - '#00264a'
    - '#5c5e5d'
    - '#d2d4d3'
    - '#ffffff'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
