name: Training
favicon: null
layout_spectrum: 0.7734306224156171
typography_spectrum: 0.028595178155228496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7801197033841163
  lightness: 0.31167499790899456
  saturation: 0.45823881262913346
  rhythmicContrast: 0.09334911638870835
purpose: []
